const colors = {
  LIGHT_BLUE: "#6EA4BF",
  BLACK: "#000",
  WHITE: "#fff",
  WHITE_FADE: "rgba(255,255,255, 0.75)",
  GRAY_FADE: "rgba(0,0,0, 0.75)"
}

export const Themes = {
  light: {
    TABS: "#41337A",
    ACTIVE_TABS: "#98CAD5",
    HEADER_GRADIENT: "#41337A",
    HEADER_GRADIENT_TWO: "rgba(65, 51, 122, 0.95)",
    HEADER_GRADIENT_THREE: "rgba(65, 51, 122, 0.60)",
    INSIDE_COMPONENT: "#98CAD5",
    INSIDE_COMPONENT_LOADING: "rgba(110,164,191,0.5)",
    INPUT_BACKGROUND: "#F3FDF6",
    DEFAULT_TEXT: colors.BLACK,
    DEFAULT_TEXT_OPACITY: colors.GRAY_FADE,
    DEFAULT_TEXT_HEADER: colors.WHITE,
    DEFAULT_TEXT_HEADER_OPACITY: colors.WHITE_FADE,
    BUTTON_TEXT_SIZE: 16,
    TITLE_FONT_SIZE: 18,
    SUBTITLE_FONT_SIZE: 12,
    PLUS_MINUS_BUTTONS_BACKGROUND: "#D9D9D9",
    AVATAR_BACKGROUND: colors.LIGHT_BLUE
  },
  dark: {}

}